config/routes.rb
Rails.application.routes.draw do
  get 'tasks', to: 'tasks#index'
  get "tasks/new", to: "tasks#new"
  get "tasks/:id", to: "tasks#show", as: :task
  
  
  post "tasks", to: "tasks#create"
  
  get "tasks/:id/edit", to: "tasks#edit"
  patch "tasks/:id", to: "tasks#update"
  
  delete "tasks/:id", to: "tasks#destroy"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :find_task, only: [:show, :edit, :update, :destroy]
  # after_action :redirect, only: [:create, :destroy]
  
  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.create(task_params)
    redirect_to tasks_path
  end

  def edit
  end

  def update
    @task.update(task_params)
    redirect_to tasks_path
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end


  private

  def find_task
    @task = Task.find(params[:id])
  end

  #def redirect
    #redirect_to tasks_path
  #end

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<%= form_for @task do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.label :completed %>
  <%= f.check_box :completed %>
  <%= f.submit%>
<% end %>

app/views/tasks/index.html.erb
<div class="index">
  <ul>
    <div class="list">
    <% %>
      <% @tasks.each do |task| %>
        <li><%= task.title %></li>
        <li><%= task.details %></li>
        <li> <% if task.completed %>
          <input type="checkbox" checked>
        <% else %>
          <input type="checkbox">
        <% end %>
        </li>
        <div class="link_class">
        <%= link_to "Check the task", task_path(task.id) %>
        </div>
        <div class="link_delete">
          <%= link_to "delete", task_path(task.id), method: :delete, data: { confirm: "Are you sure you want to delete this Task?"} %>
        </div>
      <% end %>
    </div>
  </ul>
  <div class="button">
   <button><%= link_to "Make new Task", tasks_new_path %></button> 
  </div>
</div>

app/views/tasks/new.html.erb
<%= form_for @task do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.label :completed %>
  <%= f.check_box :completed %>
  <%= f.submit%>
<% end %>

app/views/tasks/show.html.erb
<div class="show">
  <h1><%= @task.title.capitalize%></h1>
<div class="form">
  <%= form_for @task do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= f.label :details %>
    <%= f.text_field :details %>
    <%= f.label :completed %>
    <%= f.check_box :completed %>
    <%= f.submit( class: "submit") %>
  <% end %>
</div>
<br>
<div class="link">
  <button><%= link_to "Back to all the Tasks", tasks_path %></button>
</div>
</div>